// <auto-generated />
namespace Models.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.1-30610")]
    public sealed partial class modelupdatesoftdeletes : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(modelupdatesoftdeletes));
        
        string IMigrationMetadata.Id
        {
            get { return "201506051055582_model-update-softdeletes"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
